/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as partyVoteSol from "./PartyVote.sol";
export type { partyVoteSol };
export type { MockTokenContract } from "./MockTokenContract";
export type { Votoken } from "./Votoken";
