import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import { AccountProvider } from './Provider';
import { ThemeProvider } from '@/components/theme-provider';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';

import './globals.css';
import { ModeToggle } from '@/components/mode-toogle';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Vote-Chain: Decentralized Election in progress',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <AccountProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              <AppSidebar />
              <main className='flex flex-1 flex-col gap-4 p-4 pt-0 w-full h-screen'>
                <div className='flex gap-3 items-center'>
                  <SidebarTrigger />
                  <ModeToggle />
                </div>
                {children}
              </main>
            </SidebarProvider>
            <Toaster richColors position='top-right' />
          </ThemeProvider>
        </body>
      </AccountProvider>
    </html>
  );
}
