/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as partyVoteSol from "./PartyVote.sol";
export { MockTokenContract__factory } from "./MockTokenContract__factory";
export { Votoken__factory } from "./Votoken__factory";
