/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITokenContract__factory } from "./ITokenContract__factory";
export { PartyVote__factory } from "./PartyVote__factory";
