/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenContract,
  ITokenContractInterface,
} from "../../../contracts/PartyVote.sol/ITokenContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenContract__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenContractInterface {
    return new Interface(_abi) as ITokenContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenContract {
    return new Contract(address, _abi, runner) as unknown as ITokenContract;
  }
}
